---
# file: roles/cpanel/tasks/main.yml
#
# cpanel Role
# Task for handling the cPanel config and install
#

- name: Check whether cPanel is installed
  command: grep -q "Congratulations! Your installation of cPanel & WHM" /var/log/cpanel-install.log
  register: cpanel_check
  check_mode: no
  failed_when: false
  changed_when: false
  tags: cpanel

- name: Register cpanel_installed variable
  set_fact:
    cpanel_installed: true
  when: cpanel_check.rc == 0
  tags: cpanel

- name: cPanel OS Pre-requisites
  include_tasks: os.yml
  when: cpanel_installed is not defined and ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: cPanel Package Pre-requisites
  include_tasks: yum.yml
  when: cpanel_installed is not defined
  
  #- name: cPanel Folder Structure
  #  include_tasks: folders.yml
  #  when: cpanel_installed is not defined
  #
  #- name: cPanel Custom Configs
  #  include_tasks: files.yml
  #  when: cpanel_installed is not defined
  #
- name: cPanel Installer Task
  include_tasks: install.yml
  when: cpanel_installed is not defined

- name: cPanel Post Install Task
  include_tasks: post-install.yml
  when: cpanel_install_completed is defined and cpanel_install_completed.changed

- name: Get installed version of cPanel
  shell: "/usr/local/cpanel/cpanel -V"
  changed_when: false
  check_mode: no
  register: cpanel_version_raw
  tags: always

- name: Create cpanel_version variable.
  set_fact:
    cpanel_version: "{{ cpanel_version_raw.stdout.split()[0] }}"
  tags: always

- name: Create cpanel_build_version variable.
  set_fact:
    cpanel_build_version: "{{ cpanel_version_raw.stdout.split()[2].strip(')') }}"
  tags: always
